/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gui;

import java.util.List;
import ultity.*;
import objects.*;
import Connect.ObjectsData;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import models.PrintTable;

/**
 *
 * @author notte_000
 */
public class OrderPrint extends javax.swing.JDialog {
    List<Print> list;
    Client client;
    Order order;
    ObjectsData od = new ObjectsData();
    PrintTable pt;
    Validator validate = new Validator();
    
    public OrderPrint(java.awt.Frame parent, boolean modal, Client client, Order order) {
        super(parent, modal);
        initComponents();
        this.client = client;
        this.order = order;
        this.setLocationRelativeTo(rootPane);
        this.setTitle("Print");
        setValue();
    }
    
    private void setValue(){
        int vat = Math.round(order.getPrice() * 10 / 100);
        float total = order.getPrice() + vat;
        String words = NumberToWords.convert((long)total) + " dollars!";
        char[] no = String.valueOf(order.getId()).toCharArray();
        String invoiceNo = "";
        switch(no.length){
            case 1: invoiceNo = "000000" + String.valueOf(order.getId());break;
            case 2: invoiceNo = "00000" + String.valueOf(order.getId());break;
            case 3: invoiceNo = "0000" + String.valueOf(order.getId());break;
            case 4: invoiceNo = "000" + String.valueOf(order.getId());break;
            case 5: invoiceNo = "00" + String.valueOf(order.getId());break;
            case 6: invoiceNo = "0" + String.valueOf(order.getId());break;
            case 7: invoiceNo = String.valueOf(order.getId());break;
        }
        lbName.setText(client.getName());
        lbCompany.setText(client.getCompany());
        lbAddress.setText(client.getAddress());
        lbPhone.setText(client.getMobile());
        lbAmount.setText(validate.Money(order.getPrice()) + "$");
        lbNo.setText(invoiceNo);
        lbVat.setText(validate.Money(vat) + "$");
        lbTotal.setText(validate.Money(total) + "$");
        lbWords.setText(words);
        list = od.getListPrintbyOrderId(order.getId());
        pt = new PrintTable(list);
        tbPrint.setModel(pt);
        Date date = new Date(order.getOrderdate());
        SimpleDateFormat ft = new SimpleDateFormat("M/d/Y");
        lbDate.setText(ft.format(date));
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        ((DefaultTableCellRenderer)tbPrint.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        tbPrint.getColumnModel().getColumn(0).setPreferredWidth(30);
        tbPrint.getColumnModel().getColumn(1).setPreferredWidth(240);
        tbPrint.getColumnModel().getColumn(2).setPreferredWidth(50);
        tbPrint.getColumnModel().getColumn(3).setPreferredWidth(70);
        tbPrint.getColumnModel().getColumn(4).setPreferredWidth(100);
        tbPrint.getColumnModel().getColumn(5).setPreferredWidth(100);
        tbPrint.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
        tbPrint.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tbPrint.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        tbPrint.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        tbPrint.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        pnPrint.setPreferredSize(new Dimension(573, 27+(tbPrint.getRowHeight()*tbPrint.getRowCount())));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pnPrintable = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        lbCompany = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbAmount = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbVat = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        lbWords = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbNo = new javax.swing.JLabel();
        pnPrint = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPrint = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnPrint = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 2147483647));
        setMinimumSize(new java.awt.Dimension(600, 0));

        jPanel1.setMaximumSize(new java.awt.Dimension(609, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(609, 0));

        pnPrintable.setBackground(new java.awt.Color(255, 255, 255));
        pnPrintable.setMaximumSize(new java.awt.Dimension(452, 640));
        pnPrintable.setMinimumSize(new java.awt.Dimension(452, 640));
        pnPrintable.setPreferredSize(new java.awt.Dimension(452, 640));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        jLabel2.setText("Company:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("D'Hellas Joint Stock Company");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("1707 7e Rang Saint-Dominique, QC J0H 1L0, France");

        jLabel5.setText("Address:");

        jLabel6.setText("Phone:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("450-774-5737");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("VAT INVOICE");

        jLabel9.setText("Client's company:");

        lbCompany.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCompany.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbCompany.setText("lbName");

        lbName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName.setText("lbName");

        jLabel12.setText("Customer's name:");

        jLabel13.setText("Address:");

        lbAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbAddress.setText("lbName");

        jLabel15.setText("Phone number:");

        lbPhone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPhone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPhone.setText("lbName");

        jLabel17.setText("VAT Rate:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("10%");

        lbAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbAmount.setText("1000000");

        jLabel20.setText("Total Amout:");

        jLabel21.setText("VAT Amout:");

        lbVat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbVat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbVat.setText("100000");

        lbTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTotal.setText("1100000");

        jLabel24.setText("Grant Total:");

        jLabel25.setText("Grant total in words:");

        lbWords.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbWords.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbWords.setText("One million and one hunderd dollars");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Seller");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Customer");

        jLabel29.setText("Invoce No.:");

        lbNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNo.setText("0000000");

        pnPrint.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tbPrint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbPrint);

        javax.swing.GroupLayout pnPrintLayout = new javax.swing.GroupLayout(pnPrint);
        pnPrint.setLayout(pnPrintLayout);
        pnPrintLayout.setHorizontalGroup(
            pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrintLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnPrintLayout.setVerticalGroup(
            pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        jLabel10.setText("Date:");

        lbDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDate.setText("jLabel11");

        javax.swing.GroupLayout pnPrintableLayout = new javax.swing.GroupLayout(pnPrintable);
        pnPrintable.setLayout(pnPrintableLayout);
        pnPrintableLayout.setHorizontalGroup(
            pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrintableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPrintableLayout.createSequentialGroup()
                        .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(pnPrintableLayout.createSequentialGroup()
                                .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnPrintableLayout.createSequentialGroup()
                                        .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPrintableLayout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(59, 59, 59))
                                            .addGroup(pnPrintableLayout.createSequentialGroup()
                                                .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel9))
                                                .addGap(16, 16, 16)))
                                        .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbAddress)
                                                .addComponent(lbPhone, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(lbName)
                                            .addComponent(lbCompany, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPrintableLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)))
                                .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnPrintableLayout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbNo))
                                    .addGroup(pnPrintableLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbDate)))))
                        .addGap(19, 19, 19))
                    .addGroup(pnPrintableLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27)
                        .addGap(105, 105, 105))
                    .addGroup(pnPrintableLayout.createSequentialGroup()
                        .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnPrintableLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(lbWords)
                                    .addGroup(pnPrintableLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel20))
                                    .addGroup(pnPrintableLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel24)))
                                .addGap(41, 41, 41)
                                .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbVat)
                                    .addComponent(lbTotal)
                                    .addComponent(lbAmount))
                                .addGap(10, 10, 10))
                            .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnPrintableLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel7)))
                                .addComponent(pnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))))
            .addGroup(pnPrintableLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnPrintableLayout.setVerticalGroup(
            pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrintableLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnPrintableLayout.createSequentialGroup()
                        .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnPrintableLayout.createSequentialGroup()
                        .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lbDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(lbNo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPrintableLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPrintableLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(pnPrintableLayout.createSequentialGroup()
                                .addComponent(lbCompany)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbPhone)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPrintableLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbWords))
                    .addGroup(pnPrintableLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(lbAmount)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbVat)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(lbTotal))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(pnPrintableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addContainerGap(275, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnPrintable, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnPrintable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPrint);

        btnClose.setText("Close");
        btnClose.setFocusable(false);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClose);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        PrintPage p = new PrintPage(pnPrintable);
        p.print();
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbAmount;
    private javax.swing.JLabel lbCompany;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbNo;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbVat;
    private javax.swing.JLabel lbWords;
    private javax.swing.JPanel pnPrint;
    private javax.swing.JPanel pnPrintable;
    private javax.swing.JTable tbPrint;
    // End of variables declaration//GEN-END:variables
}
