/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gui;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import objects.Client;
import objects.Complaint;
import objects.Employee;
import ultity.SQLTools;

/**
 *
 * @author notte_000
 */
public class ComplaintAdd extends javax.swing.JDialog {
    Employee employee;
    Client client;
    
    public ComplaintAdd(java.awt.Frame parent, boolean modal, Employee employee) {
        super(parent, modal);
        initComponents();
        this.employee = employee;
        this.setTitle("Add a complaint");
        this.setLocationRelativeTo(rootPane);
        txtListener(txtResolve);
        rbResolved.setEnabled(false);
    }
    
    public void setClient(Client client) {
        this.client = client;
        txtClientName.setText(client.getName());
    }
    
    private void txtListener(JTextArea txtarea){
        txtarea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void removeUpdate(DocumentEvent e) {
                rbResolved.setEnabled(false);
                rbPending.setSelected(true);
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                rbResolved.setEnabled(true);
                rbResolved.setSelected(true);
            }

            @Override
            public void changedUpdate(DocumentEvent arg0) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rbResolved = new javax.swing.JRadioButton();
        rbPending = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResolve = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComplaint = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnChooseClient = new javax.swing.JButton();
        txtClientName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        rbCantResolve = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/s_add.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/s_close.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        buttonGroup1.add(rbResolved);
        rbResolved.setText("Resolved");

        buttonGroup1.add(rbPending);
        rbPending.setSelected(true);
        rbPending.setText("Pending");

        jLabel4.setText("Status:");

        txtResolve.setColumns(20);
        txtResolve.setLineWrap(true);
        txtResolve.setRows(5);
        txtResolve.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtResolveFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(txtResolve);

        jLabel3.setText("Resolve:");

        txtComplaint.setColumns(20);
        txtComplaint.setLineWrap(true);
        txtComplaint.setRows(5);
        txtComplaint.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtComplaintFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(txtComplaint);

        jLabel2.setText("Complaint:");

        btnChooseClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/s_search.png"))); // NOI18N
        btnChooseClient.setText("Choose Client");
        btnChooseClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseClientActionPerformed(evt);
            }
        });

        txtClientName.setEditable(false);

        jLabel1.setText("Client Name:");

        jLabel5.setText("Date:");

        buttonGroup1.add(rbCantResolve);
        rbCantResolve.setText("Can't resolve");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnChooseClient))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(44, 44, 44)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(53, 53, 53)
                                .addComponent(rbPending)
                                .addGap(27, 27, 27)
                                .addComponent(rbResolved)
                                .addGap(27, 27, 27)
                                .addComponent(rbCantResolve)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseClient))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbPending)
                    .addComponent(rbResolved)
                    .addComponent(rbCantResolve))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(client != null){
            String complaint = txtComplaint.getText().trim();
            String resolve = txtResolve.getText().trim();
            String cCheck[] = complaint.split(" ");
            boolean cWrong = cCheck.length > 3;
            int status = 1;
            if(rbResolved.isSelected()){
                status = 2;
            }
            else if(rbCantResolve.isSelected()){
                status = 0;
            }
            Date date = txtDate.getDate();
            SimpleDateFormat sf = new SimpleDateFormat("M/d/Y");
            String cdate = sf.format(date);
            String rdate = "";
            boolean rWrong = true;
            if(!resolve.equals("")){
                rdate = cdate;
                String rCheck[] = resolve.split(" ");
                rWrong = rCheck.length > 3;
            }
            if(cWrong == true){
                if(rWrong){
                    SQLTools st = new SQLTools();
                    Complaint cp = new Complaint(client.getId(), client.getName(), employee.getId(), complaint, resolve, cdate, rdate, status);
                    int ok = st.addComplaint(cp);
                    if(ok == 1){
                        JOptionPane.showMessageDialog(rootPane, "Complaint added!");
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Cannot add this complaint!");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "please enter more than 4 letters");
                    txtResolve.setBackground(Color.red);
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "please enter more than 4 letters");
                txtComplaint.setBackground(Color.red);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Please choose a client");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnChooseClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseClientActionPerformed
        ClientManagement cm = new ClientManagement(this, true, 2); /* 1 is order */
        cm.setVisible(true);
    }//GEN-LAST:event_btnChooseClientActionPerformed

    private void txtComplaintFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtComplaintFocusGained
        txtComplaint.setBackground(Color.white);
    }//GEN-LAST:event_txtComplaintFocusGained

    private void txtResolveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtResolveFocusGained
        txtResolve.setBackground(Color.white);
    }//GEN-LAST:event_txtResolveFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChooseClient;
    private javax.swing.JButton btnClose;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbCantResolve;
    private javax.swing.JRadioButton rbPending;
    private javax.swing.JRadioButton rbResolved;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextArea txtComplaint;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextArea txtResolve;
    // End of variables declaration//GEN-END:variables
}
