/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import javax.swing.UIManager;
import Connect.*;
import objects.Employee;
import ultity.*;

/**
 *
 * @author notte_000
 */
public class Main extends javax.swing.JFrame {
    SQLTools st = new SQLTools();
    ConnectSQL cs = new ConnectSQL();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        mnUserInformation.setEnabled(false);
        mnChangePassword.setEnabled(false);
        jMenu3.setEnabled(false);
        mnLogout.setText("Login");
        this.setLocationRelativeTo(rootPane);
    }
    
    public void closeWindows(){
        this.dispose();
    }
    
    private void callLogin(){
        MainDialog md = new MainDialog(this, true, "cardLogin");
        ObjectsData od = new ObjectsData();
        String accounttype = md.getAccountType();
        Employee employee = od.getEmployee(md.getEmployeeId());
        switch (accounttype) {
            case "admin":
                this.dispose();
                new AdminMain();
                break;
            case "employee":
                this.dispose();
                new EmployeeMain(employee);
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenuItem();
        mnConfig = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnUserInformation = new javax.swing.JMenuItem();
        mnChangePassword = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnUsersGuide = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elevation System");
        setMaximumSize(new java.awt.Dimension(76800, 57600));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jMenu1.setText("Settings");

        mnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/s_logout.png"))); // NOI18N
        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mnLogout);

        mnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/s_option.png"))); // NOI18N
        mnConfig.setText("Config");
        mnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConfigActionPerformed(evt);
            }
        });
        jMenu1.add(mnConfig);

        mnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/s_remove.png"))); // NOI18N
        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnExit);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Account");

        mnUserInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/s_information.png"))); // NOI18N
        mnUserInformation.setText("My Infomation");
        jMenu3.add(mnUserInformation);

        mnChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/s_password.png"))); // NOI18N
        mnChangePassword.setText("Change Password");
        jMenu3.add(mnChangePassword);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Help");

        mnUsersGuide.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnUsersGuide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/s_help.png"))); // NOI18N
        mnUsersGuide.setText(" Users Guide");
        mnUsersGuide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUsersGuideActionPerformed(evt);
            }
        });
        jMenu2.add(mnUsersGuide);

        mnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/s_about.png"))); // NOI18N
        mnAbout.setText(" About");
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        jMenu2.add(mnAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        callLogin();
    }//GEN-LAST:event_formWindowOpened

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        callLogin();
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnUsersGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsersGuideActionPerformed
        new MainDialog(this, true, "cardUsersGuide").setVisible(true);
    }//GEN-LAST:event_mnUsersGuideActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
        new AboutUs(this, true).setVisible(true);
    }//GEN-LAST:event_mnAboutActionPerformed

    private void mnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConfigActionPerformed
        new MainDialog(this, true, "cardConfig").setVisible(true);
    }//GEN-LAST:event_mnConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenuItem mnChangePassword;
    private javax.swing.JMenuItem mnConfig;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnUserInformation;
    private javax.swing.JMenuItem mnUsersGuide;
    // End of variables declaration//GEN-END:variables
}
